language: php

php:
  - '7.2'
  - '8.0'

services:
  - mysql

before_install:
  # disable xdebug, because it affects performance
  - phpenv config-rm xdebug.ini

  # create our test database
  - mysql -e "CREATE DATABASE IF NOT EXISTS processgraphql;"
  - mysql -e "CREATE USER 'processgraphql'@'localhost' IDENTIFIED BY 'processgraphql';"
  - mysql -e "GRANT ALL ON processgraphql.* to 'processgraphql'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"


install:
  - composer install

script:
  - composer exec -v "phpunit --bootstrap test/bootstrap.php test"

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
