<?php namespace ProcessWire;

use Youshido\GraphQL\Execution\Processor;
use ProcessWire\GraphQL\Schema;

class GraphQL extends WireData implements Module {

	/**
	 * Bootstrap the module
	 * 
	 * 
	 */
	public function init()
	{
		require_once $this->config->paths->site . 'modules/GraphQL/vendor/autoload.php';
	}

	public function execute()
	{
		// instantiating Processor and setting the schema
		$processor = new Processor(new Schema());

		if (isset($_SERVER['CONTENT_TYPE']) && $_SERVER['CONTENT_TYPE'] === 'application/json') {
				$rawBody     = file_get_contents('php://input');
				$requestData = json_decode($rawBody ?: '', true);
		} else {
				$requestData = $_POST;
		}
		$payload   = isset($requestData['query']) ? $requestData['query'] : null;
		$variables = isset($requestData['variables']) ? $requestData['variables'] : null;
		$response = $processor->processPayload($payload, $variables)->getResponseData();
		header('Content-Type: application/json');
		echo json_encode($response);
	}
  
}
