<?php namespace ProcessWire;

use GraphQL\GraphQL;
use GraphQL\Error\Debug;
use ProcessWire\GraphQL\Permissions;
use ProcessWire\HookEvent;
use ProcessWire\GraphQL\Schema;
use Processwire\ProcessGraphQLConfig;

class ProcessGraphQL extends Process implements Module {

	const pageName = 'graphql';

	public static function getModuleInfo()
	{
		return array(
			'title' => 'GraphQL',
			'version' => '1.1.2',
			'summary' => 'GraphQL for ProcessWire.',
			'href' => 'https://github.com/dadish/ProcessGraphql',
			'singular' => true,
			'autoload' => 'process=ProcessTemplate',
			'icon' => 'object-group',
      'requires' => array("PHP>=7.1", "ProcessWire>=3.0.62"),
			);
	}

	/**
	 * Bootstrap the module
	 */
	public function init()
	{
		require_once $this->config->paths->site . 'modules/ProcessGraphQL/vendor/autoload.php';
		$this->addHookAfter('Template::changed', $this, 'hookTemplateNameChange');
	}

  /**
   * Updates the legalTemplates on name change. Template names for ProcessWire
   * are not necessarily valid for GraphQL field naming. Those names that are
   * not compatible are removed from legalFields, those that are compatible
   * are updated when changed.
   * @param  HookEvent $event ProcessWire hook $event object.
   */
	public function hookTemplateNameChange(HookEvent $event)
	{
		$whatChanged = $event->arguments[0];
		$oldName = $event->arguments[1];
		$newName = $event->arguments[2];

		// do nothing if name has not changed
		if ($whatChanged !== 'name') return;

		// do nothing if template is not in legalTemplates
		if (!in_array($oldName, $this->legalTemplates)) return;

		// remove the oldName from the legalTemplates
		$index = array_search($oldName, $this->legalTemplates);
		$legalTemplates = array_slice($this->legalTemplates, 0);
		array_splice($legalTemplates, $index, 1);
		$this->message("Removed `$oldName` from the legalTemplates.");

		// if newName is compatible with the module then add it into legalTemplates
		if (ProcessGraphQLConfig::isLegalTemplateName($newName)) {
			$legalTemplates[] = $newName;
			$this->message("Added `$newName` into legalTemplaes.");
		}

		// make sure to remember changes!
		$this->modules->saveConfig($this, 'legalTemplates', $legalTemplates);
	}

  /**
   * Returns the GraphiQL GUI for ProcessWire admin when request's header is not
   * set to AJAX. Executes GraphQL api if it is AJAX.
   * @return string The rendered string of either GraphiQL GUI or GraphQL json
   * response
   */
  public function ___execute()
  {
    if ($this->config->ajax) {
    	$this->pages->setOutputFormatting(true);
    	return json_encode($this->executeGraphQL(), true);
    }
		return $this->executeGraphiQLPartial();
  }

  /**
   * Returns a GraphiQL page.
   * @return string An HTML string.
   */
  public function executeGraphiQL()
  {
		$this->setupGraphiQLAssets();
    $fullFilename = $this->config->paths->site . 'modules/ProcessGraphQL/GraphiQL/full.php';
		return wireRenderFile($fullFilename, [
			'fullGraphiQL' => true,
		]);
  }

  /**
   * Returns only the necessary parts for the GraphiQL GUI.
   * @return string An HTML strin.
   */
	public function executeGraphiQLPartial()
	{
		$this->setupGraphiQLAssets();
		$partialFilename = $this->config->paths->site . 'modules/ProcessGraphQL/GraphiQL/partial.php';
		return wireRenderFile($partialFilename, [
			'fullGraphiQL' => false,
		]);
	}

  /**
   * Setups the GraphiQL js/css assets for ProcessWire to handle in the admin.
   */
	public function setupGraphiQLAssets()
	{
		$this->config->scripts->add("https://unpkg.com/es6-promise@4.2.8/dist/es6-promise.auto.min.js");
		$this->config->scripts->add("https://unpkg.com/whatwg-fetch@3.0.0/dist/fetch.umd.js");
		$this->config->scripts->add("https://unpkg.com/react@16.12.0/umd/react.production.min.js");
		$this->config->scripts->add("https://unpkg.com/react-dom@16.12.0/umd/react-dom.production.min.js");
		$this->config->scripts->add('https://unpkg.com/graphiql@0.14.2/graphiql.min.js');
		$this->config->styles->add('https://unpkg.com/graphiql@0.14.2/graphiql.css');
		$this->config->js($this->className, [
			'GraphQLServerUrl' => $this->getGraphQLServerUrl(),
		]);
	}

  /**
   * Returns the server url from where the GraphiQL GUI will fetch the api.
   * @return string Url of the GraphQL server.
   */
	public function getGraphQLServerUrl()
	{
		$url = $this->GraphQLServerUrl;
		if (!$url) $url = $this->pages->get('template=admin, name=' . self::pageName)->url;
		return $url;
	}

	/**
	 * Retrieves the GraphQL request. Either from php://input or from $_POST.
	 * @return array An array with two properties inside. `payload` which is a
	 * GraphQL payload, that includes all operations, including query, mutation...
	 * And `variables` which is a variables object.
	 * NOTE: Both `payload` and `variables` are raw strings, that are ready to be consumed
	 * by `executeGraphQL` method
	 */
	public function getRequest()
	{
		if (isset($_SERVER['CONTENT_TYPE']) && strpos($_SERVER['CONTENT_TYPE'], 'application/json') !== false) {
				$rawBody     = file_get_contents('php://input');
				$requestData = json_decode($rawBody ?: '', true);
		} else {
				$requestData = $_POST;
		}
		$payload = isset($requestData['query']) ? $requestData['query'] : null;
		if (is_null($payload)) {
			$payload = isset($requestData['payload']) ? $requestData['payload'] : null;
		}
		$variables = isset($requestData['variables']) ? $requestData['variables'] : null;

		// in case the post is a form data, parse the variables string.
		if (is_string($variables)) {
			$variables = json_decode($variables, true);
		}
		return [
			'payload' => $payload,
			'variables' => $variables
		];
	}

  /**
   * Executes GraphQL api.
   * @return string GraphQL api JSON response.
   */
	public function ___executeGraphQL($payload = null, $variables = null)
	{
		if (!$payload) {
			$request = $this->getRequest();
			$payload = $request['payload'];
			$variables = $request['variables'];
		}

		// instantiating Processor and setting the schema
		$schema = Schema::getSchema();
		Permissions::turnOnApiAccess();
		$result = GraphQL::executeQuery($schema, $payload, $this->pages, null, $variables);
		$debug = null;
		if ($this->config->debug) {
			$debug = $debug = Debug::INCLUDE_DEBUG_MESSAGE | Debug::INCLUDE_TRACE;
		}
		$response = $result->toArray($debug);
		return $response;
	}

  /**
   * The hook for modifying the GraphQL query operation fields by the user.
   * The queryFields is an array of fields that will be set to Query operation.
	 * Custom fields could be added bu just appending them into an array.
   * See the documentation of the library used by this module to learn more
   * @see  The GraphQL lib https://github.com/webonyx/graphql-php
   * @param  $queryFields    
   * @return $queryFields
   */
  public function ___getQueryFields($queryFields)
  {
    return $queryFields;
  }

  /**
   * The hook for modifying the GraphQL mutation operation fields by the user.
   * The mutationFields is an array of fields that will be set to Mutation operation.
	 * Custom fields could be added bu just appending them into an array.
   * See the documentation of the library used by this module to learn more
   * @see  The GraphQL lib https://github.com/webonyx/graphql-php
   * @param $mutationFields
   * @return $mutationFields
   */
  public function ___getMutationFields($mutationFields)
  {
    return $mutationFields;
  }

	/**
	 * Install the module page under setup
	 */
	public function ___install()
	{
		// create the page
		$page = new Page();
		$page->template = 'admin';
		$page->name = self::pageName;

		// set parent to the home->admin->setup
		$parent = $this->pages->get($this->config->adminRootPageID)->child("name=setup, include=all");
		$page->parent = $parent;
		$page->process = $this->className;

		// set the page title as module title
		$info = self::getModuleInfo();
		$page->title = $info['title'];

		// save the page and tell the user about it
		$page->save();
		$this->message("Created page at: {$page->path}");

	}

  /**
   * Delete the module page
   */
	public function ___uninstall()
	{
		// find page by process field
		$moduleID = $this->modules->getModuleID($this);
		$page = $this->pages->get("process=$moduleID, name=" . self::pageName);

		// if the page exists then delete it and tell the user about it
		if ($page->id) {
			$this->message("Deleting page: {$page->path}");
			$page->delete();
		}
	}

}
