<?php namespace ProcessWire;

use Youshido\GraphQL\Execution\Processor;
use ProcessWire\HookEvent;
use ProcessWire\GraphQL\Schema;
use Processwire\ProcessGraphQLConfig;

class ProcessGraphQL extends Process implements Module {

	const pageName = 'graphql';

	public static function getModuleInfo()
	{
		return array(
			'title' => 'GraphQL',
			'version' => '0.10.1', 
			'summary' => 'GraphQL for ProcessWire.',
			'href' => 'https://github.com/dadish/ProcessGraphql',
			'singular' => true, 
			'autoload' => 'process=ProcessTemplate', 
			'icon' => 'object-group',
			);
	}

	/**
	 * Bootstrap the module
	 */
	public function init()
	{
		require_once $this->config->paths->site . 'modules/ProcessGraphQL/vendor/autoload.php';
		$this->addHookAfter('Template::changed', $this, 'hookTemplateNameChange');
	}

	public function hookTemplateNameChange(HookEvent $event)
	{
		$whatChanged = $event->arguments[0];
		$oldName = $event->arguments[1];
		$newName = $event->arguments[2];

		// do nothing if name has not changed
		if ($whatChanged !== 'name') return;
		
		// do nothing if template is not in legalTemplates
		if (!in_array($oldName, $this->legalTemplates)) return;
		
		// remove the oldName from the legalTemplates
		$index = array_search($oldName, $this->legalTemplates);
		$legalTemplates = array_slice($this->legalTemplates, 0);
		array_splice($legalTemplates, $index, 1);
		$this->message("Removed `$oldName` from the legalTemplates.");

		// if newName is compatible with the module then add it into legalTemplates
		if (ProcessGraphQLConfig::isLegalTemplateName($newName)) {
			$legalTemplates[] = $newName;
			$this->message("Added `$newName` into legalTemplaes.");
		}

		// make sure to remember changes!
		$this->modules->saveConfig($this, 'legalTemplates', $legalTemplates);
	}

  public function ___execute()
  {
    if ($this->config->ajax) return $this->executeGraphQL();
		return $this->executeGraphiQLPartial();
  }

  public function executeGraphiQL()
  {
		$this->setupGraphiQLAssets();
    $fullFilename = $this->config->paths->site . 'modules/ProcessGraphQL/GraphiQL/full.php';
		return wireRenderFile($fullFilename);
  }

	public function executeGraphiQLPartial()
	{
		$this->setupGraphiQLAssets();
		$partialFilename = $this->config->paths->site . 'modules/ProcessGraphQL/GraphiQL/partial.php';
		return wireRenderFile($partialFilename, [
			'fullWidth' => $this->fullWidthGraphiQL,
		]);
	}

	public function setupGraphiQLAssets()
	{
		$this->config->scripts->add($this->config->urls->ProcessGraphQL . 'GraphiQL/build/static/js/main.a8a92523.js');
		$this->config->styles->add($this->config->urls->ProcessGraphQL . 'GraphiQL/build/static/css/main.a7124171.css');
		$this->config->js($this->className, [
			'GraphQLServerUrl' => $this->getGraphQLServerUrl(),
		]);
	}

	public function getGraphQLServerUrl()
	{
		$url = $this->GraphQLServerUrl;
		if (!$url) $url = $this->pages->get('template=admin, name=' . self::pageName)->url;
		return $url;
	}

	public function executeGraphQL()
	{
		// instantiating Processor and setting the schema
		$processor = new Processor(new Schema());

		if (isset($_SERVER['CONTENT_TYPE']) && $_SERVER['CONTENT_TYPE'] === 'application/json') {
				$rawBody     = file_get_contents('php://input');
				$requestData = json_decode($rawBody ?: '', true);
		} else {
				$requestData = $_POST;
		}
		$payload   = isset($requestData['query']) ? $requestData['query'] : null;
		$variables = isset($requestData['variables']) ? $requestData['variables'] : null;
		$response = $processor->processPayload($payload, $variables)->getResponseData();
		header('Content-Type: application/json');
		return json_encode($response);
	}

	/**
	 * Install the module page under setup
	 *
	 */
	public function ___install()
	{
		// create the page
		$page = new Page();
		$page->template = 'admin';
		$page->name = self::pageName;

		// set parent to the home->admin->setup
		$page->parent = $this->pages->get($this->config->adminRootPageID)->child('name=setup');
		$page->process = $this;

		// set the page title as module title
		$info = self::getModuleInfo();
		$page->title = $info['title'];

		// save the page and tell the user about it
		$page->save();
		$this->message("Created page at: {$page->path}");
	}

	public function ___uninstall()
	{
		// find page by process field
		$moduleID = $this->modules->getModuleID($this);
		$page = $this->pages->get("process=$moduleID, name=" . self::pageName);

		// if the page exists then delete it and tell the user about it
		if ($page->id) {
			$this->message("Deleting page: {$page->path}");
			$page->delete();
		}
	}

}
