name: Release
on:
  workflow_run:
    workflows: ['Test']
    branches: [main, release]
    types: [completed]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer

      - name: Dependencies
        run: |
          npm install
          rm -rf vendor
          composer install --no-dev

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release

  update-main:
    name: Update `main`
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/stable'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Nightly Merge
        uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: 'stable'
          development_branch: 'main'
          allow_ff: true
          allow_forks: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
