name: learn-github-actions
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-lates: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Dependencies
        run: npm install

      # - name: Check Versions
      #   - run: node --version
      #   - run: php --version
      #   - run: composer --version
