name: test
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: 7.1
            phpunit: 7.4
          - php-version: 8.0
            phpunit: 9.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-lates: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
          tools: composer

      - name: Dependencies
        run: |
          composer require phpunit/phpunit ^${{ matrix.phpunit }} --dev
          composer update
          npm install
